### ISSUE TITLE
本地运行代码报错

### ISSUE THREAD

**Issue by daofeng2015** [Acmenlei/Many-people-blog#3]
ERROR  Failed to compile with 1 errors                                                                                                                                                                  16:57:25
This relative module was not found:

* ../components/Footer in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/index.vue?vue&type=script&lang=js& 

报错信息 已经npm install过了

**Comment by Acmenlei** [comment]
找一下Footer文件中的错误 ,可能哪个模块未下载 ------------------ 原始邮件 ------------------
发件人: "蒋"<notifications@github.com>
发送时间: 2020年5月16日(星期六) 下午5:01
收件人: "Acmenlei/Many-people-blog"<Many-people-blog@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Acmenlei/Many-people-blog] 本地运行代码报错 (#3)




 
ERROR  Failed to compile with 1 errors                                                                                                                                                                  16:57:25
 This relative module was not found:
  
../components/Footer in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/index.vue?vue&type=script&lang=js&
  
报错信息 已经npm install过了
 
&mdash;

**Comment by daofeng2015** [comment]
> 找一下Footer文件中的错误 ,可能哪个模块未下载 ------------------ 原始邮件 ------------------ 发件人: "蒋"<notifications@github.com> 发送时间: 2020年5月16日(星期六) 下午5:01 收件人: "Acmenlei/Many-people-blog"<Many-people-blog@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Acmenlei/Many-people-blog] 本地运行代码报错 (#3) ERROR Failed to compile with 1 errors 16:57:25 This relative module was not found: ../components/Footer in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/index.vue?vue&type=script&lang=js& 报错信息 已经npm install过了 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

默认的master版本少了Footer文件

import Footer from '../components/Footer'

**Comment by Acmenlei** [comment]
对我没有传，你自己建一个就好了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蒋"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 下午4:56
收件人:&nbsp;"Acmenlei/Many-people-blog"<Many-people-blog@noreply.github.com&gt;;
抄送:&nbsp;"我还是个孩子"<972761675@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Acmenlei/Many-people-blog] 本地运行代码报错 (#3)





  
找一下Footer文件中的错误 ,可能哪个模块未下载 ------------------ 原始邮件 ------------------ 发件人: "蒋"notifications@github.com 发送时间: 2020年5月16日(星期六) 下午5:01 收件人: "Acmenlei/Many-people-blog"Many-people-blog@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: [Acmenlei/Many-people-blog] 本地运行代码报错 (#3) ERROR Failed to compile with 1 errors 16:57:25 This relative module was not found: ../components/Footer in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/index.vue?vue&amp;type=script&amp;lang=js&amp; 报错信息 已经npm install过了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
默认的master版本少了Footer文件
 
import Footer from '../components/Footer'
